### ISSUE TITLE
Creation and modification date fields are not updated

### ISSUE THREAD

**Issue by hvelarde** [collective/transmogrify.dexterity#17]
The updater works only on fields explicitly listed in the schema:

https://github.com/collective/transmogrify.dexterity/blob/b161bcc0be88d9090803fb39babcd4b3e6b9b1ab/transmogrify/dexterity/schemaupdater.py#L88:L91

This feature is very useful when importing content from other sites.

**Comment by thet** [comment]
Those dates can only be set in a second run. If you add a content to a container, the containers modification time is changed.
I have addressed this in own migration projects with a separate pipeline, which I run after the main content import: https://github.com/thet/programmatic.transmogrifier/blob/master/src/programmatic/transmogrifier/pipeline/migrate_postwork.cfg
