### ISSUE TITLE
Add an option to remove the skip the id field or to skip some fields

### ISSUE THREAD

**Issue by ale-rt** [collective/transmogrify.dexterity#20]
As of version 1.6.1 when I am forced to remove the ids from the json generated by collective.jsonify.

The pipeline I am using is this one:

``` ini
pipeline =
    source
    constructor
    delete_id
    schemaupdater

[constructor]
blueprint = collective.transmogrifier.sections.constructor

[delete_id]
blueprint = collective.transmogrifier.sections.manipulator
delete = id

[schemaupdater]
blueprint = transmogrify.dexterity.schemaupdater

[source]
blueprint = collective.jsonmigrator.jsonsource
path=./data/plone-export
```

The `delete_id` section is taking care or removing the id.
If omitted, the objects get renamed (e.g. `front-page` becomes `front-page-1`) after [this line](https://github.com/collective/transmogrify.dexterity/blob/7e8975d5700b1fcfc97404360b09695ef0c110b4/transmogrify/dexterity/schemaupdater.py#L117) is run for the id field.

It would be interesting to have an option:
- either to skip the id field
- or to skip a list of fields

**Comment by wesleybl** [comment]
@ale-rt I fix this in https://github.com/collective/transmogrify.dexterity/pull/40
