### ISSUE TITLE
Python 3 compatibility release?

### ISSUE THREAD

**Issue by cekk** [collective/transmogrify.dexterity#36]
Can we release it with last changes from @zopyx and @cdw9 ?

**Comment by zopyx** [comment]
I don't mind - not using this module..

**Comment by cdw9** [comment]
please do! I'm not sure if all the pieces are updated to Python 3, but it would be great to still get a release out.

**Comment by wesleybl** [comment]
@cekk I created PR #39  which adds support for Python 3.
