### ISSUE TITLE
New release 2.0.0?

### ISSUE THREAD

**Issue by wesleybl** [collective/transmogrify.dexterity#46]
I made changes to the package to work with Python 3 and Plone 5.2. I performed a migration from a portal to Plone 5.2 and Python 3.8.11 with the master branch and it worked correctly.

Could someone please create a 2.0.0 release or give me permission on pypi so I can do it myself?

@lukasgraf @jone @buchi @maethu @phgross @tinagerber @njohner @thet

**Comment by maethu** [comment]
I'm no able to add you as a "releaser", but did the release 2.0.0!

--> https://pypi.org/project/transmogrify.dexterity/

Mathias

**Comment by wesleybl** [comment]
Thanks @maethu !
