### ISSUE TITLE
Can someone please make a new 3.0.0 release?

### ISSUE THREAD

**Issue by wesleybl** [collective/transmogrify.dexterity#50]
Can someone please make a new 3.0.0 release?

@lukasgraf @jone @buchi @maethu @phgross @tinagerber @njohner @thet

**Comment by wesleybl** [comment]
@lrowe can you please make a new release or give me permission on pypi so I can do it? My user there is `wesleybl`

**Comment by buchi** [comment]
@wesleybl  I've added you as a maintainer.

**Comment by wesleybl** [comment]
Thanks @buchi !

**Comment by wesleybl** [comment]
I made release 3.0.0:

https://pypi.org/project/transmogrify.dexterity/
