### ISSUE TITLE
schemaupdater attempts to set all fields in all schemas

### ISSUE THREAD

**Issue by cewing** [collective/transmogrify.dexterity#7]
This can cause problems if you have read-only fields in a schema.  

This could be solved in one of two ways.  One could skip any fields in any schemas *not* in the current `item`.  This would bring the schemaupdater in line with how the current AT schemaupdater works.  Alternatively, a config option for `omit_fields` could be added which would allow the user to determine which fields to skip over during updating.  

Any thoughts on this?

**Comment by hvelarde** [comment]
This is fixed in master branch: https://github.com/collective/transmogrify.dexterity/blob/b161bcc0be88d9090803fb39babcd4b3e6b9b1ab/transmogrify/dexterity/schemaupdater.py#L92:L93
